Public Class Form1

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        If TextBox1.Text = "Австрия" Then
            PictureBox1.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Балкански полуостров"
            TextBox4.Text = "83 879 km²"
            TextBox5.Text = "8 898 457 души"
            TextBox6.Text = "Виена"
            TextBox7.Text = "1 888 776 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "България" Then
            PictureBox2.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Балкански полуостров"
            TextBox4.Text = "110 993,6 km²"
            TextBox5.Text = "6 951 482 души"
            TextBox6.Text = "София"
            TextBox7.Text = "1 286 383 души"
            PictureBox1.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "Полша" Then
            PictureBox3.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Централна Европа"
            TextBox4.Text = "312 683 km²"
            TextBox5.Text = "38 386 000 души"
            TextBox6.Text = "Варшава"
            TextBox7.Text = "1 764 615 души"
            PictureBox2.Visible = False
            PictureBox1.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "румъния" Then
            PictureBox4.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Балкански полуостров"
            TextBox4.Text = "238 397 km²"
            TextBox5.Text = "20 121 641 души"
            TextBox6.Text = "Букурещ"
            TextBox7.Text = "2 106 144 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox1.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "Франция" Then
            PictureBox5.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Западна Европа"
            TextBox4.Text = "643 801 km²"
            TextBox5.Text = " 67 348 000 души"
            TextBox6.Text = "Париж"
            TextBox7.Text = "2 140 526 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox1.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "Германия" Then
            PictureBox6.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Централна Европа"
            TextBox4.Text = "357 386 km²"
            TextBox5.Text = "83 019 200 души"
            TextBox6.Text = "Берлин"
            TextBox7.Text = "3 748 148 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox1.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "Гърция" Then
            PictureBox7.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Балкански полуостров"
            TextBox4.Text = "131 957 km²"
            TextBox5.Text = "10 768 477 души"
            TextBox6.Text = "Атина"
            TextBox7.Text = "664 046 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox1.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "Испания" Then
            PictureBox8.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Пиренейски полуостров"
            TextBox4.Text = "505 990 km²"
            TextBox5.Text = "46 733 038 души"
            TextBox6.Text = "Мадрид"
            TextBox7.Text = "3 165 235 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox1.Visible = False
            PictureBox9.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "Италия" Then
            PictureBox9.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Апенинския полуостров"
            TextBox4.Text = "301 338 km²"
            TextBox5.Text = "60 359 546 души"
            TextBox6.Text = "Рим"
            TextBox7.Text = "2 872 659 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox1.Visible = False
            PictureBox10.Visible = False
        ElseIf TextBox1.Text = "Люксембург" Then
            PictureBox10.Visible = True
            TextBox2.Text = "Европа"
            TextBox3.Text = "Северозападна Европа"
            TextBox4.Text = "2586,4  km²"
            TextBox5.Text = "613 894 души"
            TextBox6.Text = "Люксембург"
            TextBox7.Text = "116 323 души"
            PictureBox2.Visible = False
            PictureBox3.Visible = False
            PictureBox4.Visible = False
            PictureBox5.Visible = False
            PictureBox6.Visible = False
            PictureBox7.Visible = False
            PictureBox8.Visible = False
            PictureBox9.Visible = False
            PictureBox1.Visible = False
        End If
    End Sub
End Class
